### ISSUE TITLE
curly brace on imports

### ISSUE THREAD

**Issue by mikebutts** [ccml/bwa-u3-jammming-prj#2]
import Playlist from '../Playlist/Playlist';
import SearchBar from '../SearchBar/SearchBar';
import SearchResults from '../SearchResults/SearchResults';
import Spotify from '../../util/Spotify';

when importing you only need curly braces on non default components (functions)

https://stackoverflow.com/questions/36795819/when-should-i-use-curly-braces-for-es6-import/36796281

**Comment by ccml** [comment]
Ok
