### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by mikebutts** [ccml/bwa-u3-jammming-prj#6]
https://github.com/ccml/bwa-u3-jammming-prj/blob/55965c352a2f2ae425eef9ec15ba18b265885f07/jamming/src/Components/Track/Track.js#L3

where are you addTrack, removeTrack and renderAction() ?

**Comment by ccml** [comment]
These functions are not needed in my solution. The Track component doesn't know what the action does (add a track, remove a track or what else). The Track component receive the 'onAction' callback that does the job. That call back is passed from the components "SearchResults" and "PlayList" to the component "TrackList". And the component "TrackList" forward the callback to each "Track".
