### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mikebutts** [ccml/bwa-u3-jammming-prj#7]
Grade:  Needs improvement.

Summary: I could not get this project to run, it threw client errors so I went through the code without seeing it. You did a good job of keeping the code neat, I was easily able to read your code. There seems to be a few mission Track functions which I added a ticket for. Take a look at the issues open and go over the code, refer back to lessons to help do this, ask in slack or ask advisors for help.

**Comment by ccml** [comment]
The project works. I suppose the client errors you had is due to the fact I removed the Spotify clientid in the Spotify.js file before pushing the code.

Regards.

**Comment by ccml** [comment]
I have commited now the source code with the clientid. Which is not very good at a security point of vue.
